### ISSUE TITLE
Error whilst running the example with my own latitude and longitude values

### ISSUE THREAD

**Issue by Amj2d** [jld3103/osm-nominatim#1]
Hi. 
Im new here.  Im using Flutter.  

Running the example code works fine.  However when I substitute for my own lat and lon values I get the error below.
I am using package:geolocator/geolocator.dart to get my currentPosition

E/flutter ( 1901): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: type 'int' is not a subtype of type 'double' in type cast
E/flutter ( 1901): #0      new Place.fromJson (package:osm_nominatim/osm_nominatim.dart:277:40)
E/flutter ( 1901): #1      Nominatim.reverseSearch (package:osm_nominatim/osm_nominatim.dart:239:18)
E/flutter ( 1901): <asynchronous suspension>

Any help would be appreciated.
Thanks

**Comment by provokateurin** [comment]
I also ran into that issue. I'll push it now

**Comment by provokateurin** [comment]
Fixed in version `1.0.1`.

**Comment by provokateurin** [comment]
One question: How did you find this package?

**Comment by Amj2d** [comment]
Hi.
I was googling open street maps api for flutter and I came across a link to the package on pub.dev

I haven't had a chance to try out the fix yet.  But thanks for a super speedy response.
