### ISSUE TITLE
Request to update zoom capability

### ISSUE THREAD

**Issue by syednasharudin** [jld3103/osm-nominatim#10]
Hi, i found that you are allowing to send zoom as one of the attribute in `Nominatim.reverseSearch` method, but seems like it is not being used and send to the api. Would you mind to allow it by adding it at osm_nominatime.dart line 222 as follows:

final uri = Uri.https(
      host,
      '/reverse',
      {
        'format': 'jsonv2',
        'zoom': zoom.toString(), // --> to allow zoom to be used
        if (lat != null) 'lat': lat.toString(),
        if (lon != null) 'lon': lon.toString(),
        if (osmType != null) 'osm_type': osmType,
        if (osmId != null) 'osm_id': osmId.toString(),
        if (addressDetails) 'addressdetails': '1',
        if (extraTags) 'extratags': '1',
        if (nameDetails) 'namedetails': '1',
        if (language != null) 'accept-language': language,
      },
    );

**Comment by provokateurin** [comment]
Could create a PR for this fix, please?

**Comment by syednasharudin** [comment]
PR: https://github.com/provokateurin/osm-nominatim/pull/11

**Comment by provokateurin** [comment]
Released as 3.0.1
