### ISSUE TITLE
Loss of accuracy, noticed by change of postcode.

### ISSUE THREAD

**Issue by Amj2d** [jld3103/osm-nominatim#2]
Hi. 
I have a postcode of DE23 6PF.
I pass in its longitude of 52.90662648294178
and latitude of -1.4952446502773815
to the Nominatim.reverseSearch function

when I do a 
print(reverseSearchResult.displayName);
the postcode returned is DE23 6PE     ------- different to above postcode

when I 
      print(reverseSearchResult.lat);
      print(reverseSearchResult.lon);
the lat is 52.90656985
the lon is -1.4952764100693687    -------- different to the lat and lon values passed in to the reverseSearch function

Any help to fix this would be appreciated.
Thanks

**Comment by provokateurin** [comment]
This is not fixable in this library, because it only interfaces the OSM Nominatim API. Their database has that data and there is noting to change about it. Sorry for that

**Comment by Amj2d** [comment]
Ok, thanks again.

I was just unsure as to why the values passed to the function were changed slightly, noticed by a change of postcode.  Surely they should remain unchanged.
