### ISSUE TITLE
NoSuchMethodError (NoSuchMethodError: The method 'map' was called on null. Receiver: null Tried calling: map<String>(Closure: (dynamic) => String))

### ISSUE THREAD

**Issue by JoergPf** [jld3103/osm-nominatim#4]
Hi,

I did a test with coordinates on sea:
lat: 54.75220588224341
lng: 7.621583734613374

The query breaks with:
NoSuchMethodError (NoSuchMethodError: The method 'map' was called on null. Receiver: null Tried calling: map<String>(Closure: (dynamic) => String))

Is there a way I can avoid this or is this a bug?

**Comment by provokateurin** [comment]
I think that is the expected result because nothing was found. Maybe returning an empty list would be better.

**Comment by provokateurin** [comment]
Can you send the exact code you used? I'm hitting some error, but it's something else than your message

**Comment by JoergPf** [comment]
final reverseSearchResult = await Nominatim.reverseSearch(
      lat: 54.75220588224341,
      lon: 7.621583734613374,
      addressDetails: true,
      extraTags: false,
      nameDetails: false,
    );

**Comment by provokateurin** [comment]
I'm only getting `type 'Null' is not a subtype of type 'int' in type cast`, but my fix should also fix what you see.

**Comment by provokateurin** [comment]
I published 2.0.1 which should fix the issue. Can you test it?

**Comment by JoergPf** [comment]
Great, now it's throwing an exception! Thanks for fixing!
